// static_pages/src/lib/components/Footer.svelte
<script lang="ts">
    import axios from "axios";
    import { Mail, Phone } from "lucide-svelte";

    const apiUrl: string =
        import.meta.env.MODE === "development"
            ? import.meta.env.VITE_DEV_URL
            : import.meta.env.VITE_PROD_URL;

    type FormData = {
        name: string;
        email: string;
        mobile: string;
        thought: string;
    };

    let formData: FormData = { name: "", email: "", mobile: "", thought: "" };
    let status: "idle" | "loading" | "success" | "error" = "idle";

    const handleChange = (e: Event) => {
        const target = e.target as HTMLInputElement | HTMLTextAreaElement;
        formData = { ...formData, [target.name]: target.value };
    };

    const handleSubmit = async (e: Event) => {
        e.preventDefault();
        status = "loading";

        try {
            await axios.post(`${apiUrl}/api/sendEmail`, formData, {
                headers: { "Content-Type": "application/json" },
            });

            status = "success";
            formData = { name: "", email: "", mobile: "", thought: "" };
        } catch (error: any) {
            status = "error";
        } finally {
            setTimeout(() => (status = "idle"), 4000);
        }
    };
</script>

<footer
    id="contact-section"
    class="w-full py-8 sm:py-12 px-4 sm:px-6 bg-transparent text-slate-700"
>
    <div
        class="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-10"
    >
        <!-- Left Section -->
        <div
            class="flex flex-col justify-center text-center md:text-left space-y-4 sm:space-y-6"
        >
            <h2 class="text-xl sm:text-2xl font-semibold text-(--brand-blue)">
                Protect your data, infrastructure, and operations.
            </h2>
            <p class="text-base sm:text-lg">
                Partner with
                <span class="font-semibold text-(--brand-orange)"
                    >Krya Solutions</span
                >
                for end-to-end cyber protection tailored to your needs.
            </p>

            <div
                class="flex flex-col items-center md:items-start gap-3 sm:gap-4 mt-2 text-(--brand-blue)"
            >
                <a
                    href="tel:+914466692727"
                    class="flex items-center gap-2 hover:text-(--brand-orange) transition-colors duration-200 whitespace-nowrap"
                >
                    <Phone class="w-4 h-4 sm:w-5 sm:h-5 shrink-0" />
                    <span class="text-sm sm:text-base">+91 44 6669 2727</span>
                </a>
                <a
                    href="mailto:ks-info@kryasolutions.com"
                    class="flex items-center gap-2 hover:text-(--brand-orange) transition-colors duration-200 whitespace-nowrap break-all sm:break-normal"
                >
                    <Mail class="w-4 h-4 sm:w-5 sm:h-5 shrink-0" />
                    <span class="text-sm sm:text-base"
                        >ks-info@kryasolutions.com</span
                    >
                </a>
            </div>
        </div>

        <!-- Right Section - Contact Form -->
        <div class="rounded-2xl shadow-xl bg-white/5 p-4 sm:p-6 md:p-8">
            <h3
                class="text-lg sm:text-xl font-semibold mb-4 text-center md:text-left"
            >
                Contact Us
            </h3>
            <form
                on:submit|preventDefault={handleSubmit}
                class="space-y-3 sm:space-y-4"
            >
                <div>
                    <label for="name" class="block text-xs sm:text-sm mb-1"
                        >Name</label
                    >
                    <input
                        type="text"
                        name="name"
                        bind:value={formData.name}
                        on:input={handleChange}
                        required
                        class="w-full px-3 sm:px-4 py-2 text-sm sm:text-base rounded-md border border-(--brand-blue)/10 focus:outline-none focus:border-(--brand-blue)/40 text-slate-700 placeholder-slate-400 transition-colors duration-200"
                    />
                </div>
                <div>
                    <label for="name" class="block text-xs sm:text-sm mb-1"
                        >Email</label
                    >
                    <input
                        type="email"
                        name="email"
                        bind:value={formData.email}
                        on:input={handleChange}
                        required
                        class="w-full px-3 sm:px-4 py-2 text-sm sm:text-base rounded-md border border-(--brand-blue)/10 focus:outline-none focus:border-(--brand-blue)/40 text-slate-700 placeholder-slate-400 transition-colors duration-200"
                    />
                </div>
                <div>
                    <label for="mobile" class="block text-xs sm:text-sm mb-1"
                        >Mobile No.</label
                    >
                    <input
                        type="text"
                        name="mobile"
                        bind:value={formData.mobile}
                        on:input={handleChange}
                        required
                        class="w-full px-3 sm:px-4 py-2 text-sm sm:text-base rounded-md border border-(--brand-blue)/10 focus:outline-none focus:border-(--brand-blue)/40 text-slate-700 placeholder-slate-400 transition-colors duration-200"
                    />
                </div>
                <div>
                    <label for="thoughts" class="block text-xs sm:text-sm mb-1"
                        >Share your thoughts</label
                    >
                    <textarea
                        name="thought"
                        rows="4"
                        bind:value={formData.thought}
                        on:input={handleChange}
                        required
                        class="w-full px-3 sm:px-4 py-2 text-sm sm:text-base rounded-md border border-(--brand-blue)/10 focus:outline-none focus:border-(--brand-blue)/40 text-slate-700 placeholder-slate-400 transition-colors duration-200"
                    ></textarea>
                </div>
                <button
                    type="submit"
                    disabled={status === "loading"}
                    class="w-full bg-(--brand-orange) text-white py-2.5 sm:py-3 rounded-full font-medium text-sm sm:text-base transition-all duration-300 hover:scale-102 hover:shadow-lg hover:shadow-(--brand-orange)/20 disabled:opacity-60 disabled:hover:scale-100 disabled:hover:shadow-none"
                >
                    {#if status === "loading"}
                        Sending...
                    {:else if status === "success"}
                        Sent!
                    {:else}
                        Submit
                    {/if}
                </button>

                {#if status === "success"}
                    <p
                        class="text-(--brand-blue) text-xs sm:text-sm text-center mt-2 font-medium"
                    >
                        Message sent successfully!
                    </p>
                {/if}
                {#if status === "error"}
                    <p class="text-red-400 text-xs sm:text-sm text-center mt-2">
                        Failed to send. Please try again.
                    </p>
                {/if}
            </form>
        </div>
    </div>

    <div
        class="mt-8 sm:mt-12 pt-4 text-center text-xs sm:text-sm text-slate-500"
    >
        © {new Date().getFullYear()} Krya Solutions. All rights reserved.
    </div>
</footer>

// kyd/src/components/Footer.tsx
import axios from "axios";
import { useState } from "react";
import { Mail, Phone } from "lucide-react";

const apiUrl: string =
    import.meta.env.MODE === "development"
        ? import.meta.env.VITE_DEV_URL
        : import.meta.env.VITE_PROD_URL;

const Footer = () => {
    type FormData = {
        name: string;
        email: string;
        mobile: string;
        thought: string;
    };

    const [formData, setFormData] = useState<FormData>({
        name: "",
        email: "",
        mobile: "",
        thought: "",
    });

    const [status, setStatus] = useState<
        "idle" | "loading" | "success" | "error"
    >("idle");

    const handleChange = (
        e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
    ) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setStatus("loading");

        try {
            await axios.post(`${apiUrl}/api/sendEmail`, formData, {
                headers: { "Content-Type": "application/json" },
            });

            setStatus("success");
            setFormData({ name: "", email: "", mobile: "", thought: "" });
        } catch (error: any) {
            setStatus("error");
        } finally {
            setTimeout(() => setStatus("idle"), 4000);
        }
    };

    return (
        <footer
            id="contact-section"
            className="w-full py-12 px-6 text-slate-700"
        >
            <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-10">
                {/* Left Section */}
                <div className="flex flex-col justify-center text-center md:text-left space-y-6">
                    <h2 className="text-2xl font-semibold text-(--brand-blue)">
                        Protect your data, infrastructure, and operations.
                    </h2>
                    <p className="text-lg">
                        Partner with{" "}
                        <span className="font-semibold text-(--brand-orange)">
                            Krya Solutions
                        </span>{" "}
                        for end-to-end cyber protection tailored to your needs.
                    </p>

                    <div className="flex flex-col sm:flex-row sm:justify-start justify-center gap-4 mt-2 text-(--brand-blue)">
                        <a
                            href="tel:+914466692727"
                            className="flex items-center justify-center gap-2 hover:text-(--brand-orange) transition"
                        >
                            <Phone className="w-5 h-5" />
                            <span>+91 44 6669 2727</span>
                        </a>
                        <a
                            href="mailto:ks-info@kryasolutions.com"
                            className="flex items-center justify-center gap-2 transition hover:text-(--brand-orange)"
                        >
                            <Mail className="w-5 h-5" />
                            <span>ks-info@kryasolutions.com</span>
                        </a>
                    </div>
                </div>

                {/* Right Section - Contact Form */}
                <div className="bg-white/5 text-slate-700 rounded-2xl shadow-lg p-6 md:p-8">
                    <h3 className="text-xl font-semibold mb-4 text-center md:text-left">
                        Contact Us
                    </h3>
                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div>
                            <label className="block text-sm mb-1">Name</label>
                            <input
                                type="text"
                                name="name"
                                value={formData.name}
                                onChange={handleChange}
                                required
                                className="w-full px-4 py-2 rounded-md border border-(--brand-blue)/10 focus:outline-none focus:border-(--brand-blue)/40 text-slate-700"
                            />
                        </div>
                        <div>
                            <label className="block text-sm mb-1">Email</label>
                            <input
                                type="email"
                                name="email"
                                value={formData.email}
                                onChange={handleChange}
                                required
                                className="w-full px-4 py-2 rounded-md border border-(--brand-blue)/10 focus:outline-none focus:border-(--brand-blue)/40 text-slate-700"
                            />
                        </div>
                        <div>
                            <label className="block text-sm mb-1">
                                Mobile No.
                            </label>
                            <input
                                type="text"
                                name="mobile"
                                value={formData.mobile}
                                onChange={handleChange}
                                required
                                className="w-full px-4 py-2 rounded-md border border-(--brand-blue)/10 focus:outline-none focus:border-(--brand-blue)/40 text-slate-700"
                            />
                        </div>
                        <div>
                            <label className="block text-sm mb-1">
                                Share your thoughts
                            </label>
                            <textarea
                                name="thought"
                                rows={4}
                                value={formData.thought}
                                onChange={handleChange}
                                required
                                className="w-full px-4 py-2 rounded-md border border-(--brand-blue)/10 focus:outline-none focus:border-(--brand-blue)/40 text-slate-700"
                            ></textarea>
                        </div>
                        <button
                            type="submit"
                            disabled={status === "loading"}
                            className="w-full bg-(--brand-orange) text-white py-2 rounded-md font-medium transition-transform duration-300 disabled:opacity-60 hover:scale-105"
                        >
                            {status === "loading"
                                ? "Sending..."
                                : status === "success"
                                  ? "Sent!"
                                  : "Submit"}
                        </button>

                        {status === "success" && (
                            <p className="text-green-400 text-sm text-center mt-2">
                                Message sent successfully!
                            </p>
                        )}
                        {status === "error" && (
                            <p className="text-red-400 text-sm text-center mt-2">
                                Failed to send. Please try again.
                            </p>
                        )}
                    </form>
                </div>
            </div>

            <div className="mt-12 pt-4 text-center text-sm text-slate-500">
                © {new Date().getFullYear()} Krya Solutions. All rights
                reserved.
            </div>
        </footer>
    );
};

export default Footer;
